apiVersion: apps/v1
kind: Deployment
metadata:
  name: econsume-service
  labels:
    app: econsume
    tier: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: econsume-service
  template:
    metadata:
      labels:
        app: econsume-service
    spec:
      containers:
        - name: econsume-service
          image: artifactory.demo.com/econsume/econsume-demo:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
            - containerPort: 8081
            - protocol: TCP
          resources:
            requests:
              memory: "1024Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1"